#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>
#include <QMainWindow>

class View;

namespace Ui {
    class MainWindow;
}

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();
protected:
    void closeEvent(QCloseEvent *e) override;
private:
    // Auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

private slots:
    void directionalLightRChanged(int newValue);
    void directionalLightGChanged(int newValue);
    void directionalLightBChanged(int newValue);
    void crepuscularRaysChanged(bool newValue);
    void shadowMappingChanged(bool newValue);
    void hdrChanged(bool newValue);
    void hdrExposureChanged(int newValue);
    void geometryShadersChanged(bool newValue);
};

#endif // MAINWINDOW_H
